//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EPDDLParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IEPDDLParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class EPDDLParserBaseListener : IEPDDLParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.mainDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMainDef([NotNull] EPDDLParser.MainDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.mainDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMainDef([NotNull] EPDDLParser.MainDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.domainDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDomainDef([NotNull] EPDDLParser.DomainDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.domainDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDomainDef([NotNull] EPDDLParser.DomainDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.libraryDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLibraryDef([NotNull] EPDDLParser.LibraryDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.libraryDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLibraryDef([NotNull] EPDDLParser.LibraryDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.problemDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProblemDef([NotNull] EPDDLParser.ProblemDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.problemDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProblemDef([NotNull] EPDDLParser.ProblemDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.domainItemDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDomainItemDef([NotNull] EPDDLParser.DomainItemDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.domainItemDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDomainItemDef([NotNull] EPDDLParser.DomainItemDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.libraryItemDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLibraryItemDef([NotNull] EPDDLParser.LibraryItemDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.libraryItemDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLibraryItemDef([NotNull] EPDDLParser.LibraryItemDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.problemItemDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProblemItemDef([NotNull] EPDDLParser.ProblemItemDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.problemItemDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProblemItemDef([NotNull] EPDDLParser.ProblemItemDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.domainLibrariesNameDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDomainLibrariesNameDef([NotNull] EPDDLParser.DomainLibrariesNameDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.domainLibrariesNameDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDomainLibrariesNameDef([NotNull] EPDDLParser.DomainLibrariesNameDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.problemDomainNameDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProblemDomainNameDef([NotNull] EPDDLParser.ProblemDomainNameDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.problemDomainNameDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProblemDomainNameDef([NotNull] EPDDLParser.ProblemDomainNameDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.agentNamesDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAgentNamesDef([NotNull] EPDDLParser.AgentNamesDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.agentNamesDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAgentNamesDef([NotNull] EPDDLParser.AgentNamesDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.agentGroupsListDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAgentGroupsListDef([NotNull] EPDDLParser.AgentGroupsListDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.agentGroupsListDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAgentGroupsListDef([NotNull] EPDDLParser.AgentGroupsListDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.agentGroupDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAgentGroupDef([NotNull] EPDDLParser.AgentGroupDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.agentGroupDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAgentGroupDef([NotNull] EPDDLParser.AgentGroupDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.objectNamesDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectNamesDef([NotNull] EPDDLParser.ObjectNamesDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.objectNamesDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectNamesDef([NotNull] EPDDLParser.ObjectNamesDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.staticPredListDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStaticPredListDef([NotNull] EPDDLParser.StaticPredListDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.staticPredListDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStaticPredListDef([NotNull] EPDDLParser.StaticPredListDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.requireDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRequireDef([NotNull] EPDDLParser.RequireDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.requireDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRequireDef([NotNull] EPDDLParser.RequireDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.typesDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypesDef([NotNull] EPDDLParser.TypesDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.typesDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypesDef([NotNull] EPDDLParser.TypesDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.predicateListDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateListDef([NotNull] EPDDLParser.PredicateListDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.predicateListDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateListDef([NotNull] EPDDLParser.PredicateListDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.predicateDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateDef([NotNull] EPDDLParser.PredicateDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.predicateDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateDef([NotNull] EPDDLParser.PredicateDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionDef([NotNull] EPDDLParser.ActionDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionDef([NotNull] EPDDLParser.ActionDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.parametersDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParametersDef([NotNull] EPDDLParser.ParametersDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.parametersDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParametersDef([NotNull] EPDDLParser.ParametersDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.modalityDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModalityDef([NotNull] EPDDLParser.ModalityDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.modalityDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModalityDef([NotNull] EPDDLParser.ModalityDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.observabilityGroupsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObservabilityGroupsDef([NotNull] EPDDLParser.ObservabilityGroupsDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.observabilityGroupsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObservabilityGroupsDef([NotNull] EPDDLParser.ObservabilityGroupsDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventDef([NotNull] EPDDLParser.EventDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventDef([NotNull] EPDDLParser.EventDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventPreDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventPreDef([NotNull] EPDDLParser.EventPreDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventPreDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventPreDef([NotNull] EPDDLParser.EventPreDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventPostDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventPostDef([NotNull] EPDDLParser.EventPostDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventPostDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventPostDef([NotNull] EPDDLParser.EventPostDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.postconditionBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostconditionBlock([NotNull] EPDDLParser.PostconditionBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.postconditionBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostconditionBlock([NotNull] EPDDLParser.PostconditionBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.postcondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostcondition([NotNull] EPDDLParser.PostconditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.postcondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostcondition([NotNull] EPDDLParser.PostconditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.simplePostcondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimplePostcondition([NotNull] EPDDLParser.SimplePostconditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.simplePostcondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimplePostcondition([NotNull] EPDDLParser.SimplePostconditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionTypeDef([NotNull] EPDDLParser.ActionTypeDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionTypeDef([NotNull] EPDDLParser.ActionTypeDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateDef([NotNull] EPDDLParser.StateDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateDef([NotNull] EPDDLParser.StateDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.initDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitDef([NotNull] EPDDLParser.InitDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.initDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitDef([NotNull] EPDDLParser.InitDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.goalDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGoalDef([NotNull] EPDDLParser.GoalDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.goalDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGoalDef([NotNull] EPDDLParser.GoalDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionConditionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionConditionDef([NotNull] EPDDLParser.ActionConditionDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionConditionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionConditionDef([NotNull] EPDDLParser.ActionConditionDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeSignatureDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionTypeSignatureDef([NotNull] EPDDLParser.ActionTypeSignatureDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeSignatureDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionTypeSignatureDef([NotNull] EPDDLParser.ActionTypeSignatureDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionPreDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionPreDef([NotNull] EPDDLParser.ActionPreDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionPreDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionPreDef([NotNull] EPDDLParser.ActionPreDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionObsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionObsDef([NotNull] EPDDLParser.ActionObsDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionObsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionObsDef([NotNull] EPDDLParser.ActionObsDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.typedIdentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedIdentList([NotNull] EPDDLParser.TypedIdentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.typedIdentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedIdentList([NotNull] EPDDLParser.TypedIdentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.typedVariableList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedVariableList([NotNull] EPDDLParser.TypedVariableListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.typedVariableList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedVariableList([NotNull] EPDDLParser.TypedVariableListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] EPDDLParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] EPDDLParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.reservedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReservedType([NotNull] EPDDLParser.ReservedTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.reservedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReservedType([NotNull] EPDDLParser.ReservedTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.formula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormula([NotNull] EPDDLParser.FormulaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.formula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormula([NotNull] EPDDLParser.FormulaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.conditionFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionFormula([NotNull] EPDDLParser.ConditionFormulaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.conditionFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionFormula([NotNull] EPDDLParser.ConditionFormulaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] EPDDLParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] EPDDLParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.atomicCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicCondition([NotNull] EPDDLParser.AtomicConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.atomicCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicCondition([NotNull] EPDDLParser.AtomicConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.predicateFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateFormula([NotNull] EPDDLParser.PredicateFormulaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.predicateFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateFormula([NotNull] EPDDLParser.PredicateFormulaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.atomicEqFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicEqFormula([NotNull] EPDDLParser.AtomicEqFormulaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.atomicEqFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicEqFormula([NotNull] EPDDLParser.AtomicEqFormulaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] EPDDLParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] EPDDLParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.groundTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroundTerm([NotNull] EPDDLParser.GroundTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.groundTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroundTerm([NotNull] EPDDLParser.GroundTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.modality"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModality([NotNull] EPDDLParser.ModalityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.modality"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModality([NotNull] EPDDLParser.ModalityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.singleModality"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleModality([NotNull] EPDDLParser.SingleModalityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.singleModality"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleModality([NotNull] EPDDLParser.SingleModalityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.groupModality"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupModality([NotNull] EPDDLParser.GroupModalityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.groupModality"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupModality([NotNull] EPDDLParser.GroupModalityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.modalityLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModalityLabel([NotNull] EPDDLParser.ModalityLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.modalityLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModalityLabel([NotNull] EPDDLParser.ModalityLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.modalityAgent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModalityAgent([NotNull] EPDDLParser.ModalityAgentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.modalityAgent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModalityAgent([NotNull] EPDDLParser.ModalityAgentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.modalityAgentGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModalityAgentGroup([NotNull] EPDDLParser.ModalityAgentGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.modalityAgentGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModalityAgentGroup([NotNull] EPDDLParser.ModalityAgentGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.allAgents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllAgents([NotNull] EPDDLParser.AllAgentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.allAgents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllAgents([NotNull] EPDDLParser.AllAgentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.predicateName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateName([NotNull] EPDDLParser.PredicateNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.predicateName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateName([NotNull] EPDDLParser.PredicateNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.domainName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDomainName([NotNull] EPDDLParser.DomainNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.domainName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDomainName([NotNull] EPDDLParser.DomainNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.problemName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProblemName([NotNull] EPDDLParser.ProblemNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.problemName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProblemName([NotNull] EPDDLParser.ProblemNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.libraryName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLibraryName([NotNull] EPDDLParser.LibraryNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.libraryName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLibraryName([NotNull] EPDDLParser.LibraryNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateName([NotNull] EPDDLParser.StateNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateName([NotNull] EPDDLParser.StateNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.worldName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWorldName([NotNull] EPDDLParser.WorldNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.worldName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWorldName([NotNull] EPDDLParser.WorldNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionName([NotNull] EPDDLParser.ActionNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionName([NotNull] EPDDLParser.ActionNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventName([NotNull] EPDDLParser.EventNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventName([NotNull] EPDDLParser.EventNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.agentName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAgentName([NotNull] EPDDLParser.AgentNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.agentName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAgentName([NotNull] EPDDLParser.AgentNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.modalityName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModalityName([NotNull] EPDDLParser.ModalityNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.modalityName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModalityName([NotNull] EPDDLParser.ModalityNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.staticPredDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStaticPredDef([NotNull] EPDDLParser.StaticPredDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.staticPredDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStaticPredDef([NotNull] EPDDLParser.StaticPredDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.genericName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericName([NotNull] EPDDLParser.GenericNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.genericName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericName([NotNull] EPDDLParser.GenericNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateWorldsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateWorldsDef([NotNull] EPDDLParser.StateWorldsDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateWorldsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateWorldsDef([NotNull] EPDDLParser.StateWorldsDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateRelDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateRelDef([NotNull] EPDDLParser.StateRelDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateRelDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateRelDef([NotNull] EPDDLParser.StateRelDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateRelations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateRelations([NotNull] EPDDLParser.StateRelationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateRelations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateRelations([NotNull] EPDDLParser.StateRelationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.worldRelation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWorldRelation([NotNull] EPDDLParser.WorldRelationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.worldRelation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWorldRelation([NotNull] EPDDLParser.WorldRelationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.worldNamePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWorldNamePair([NotNull] EPDDLParser.WorldNamePairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.worldNamePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWorldNamePair([NotNull] EPDDLParser.WorldNamePairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateValDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateValDef([NotNull] EPDDLParser.StateValDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateValDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateValDef([NotNull] EPDDLParser.StateValDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateValuation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateValuation([NotNull] EPDDLParser.StateValuationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateValuation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateValuation([NotNull] EPDDLParser.StateValuationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.worldValuation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWorldValuation([NotNull] EPDDLParser.WorldValuationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.worldValuation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWorldValuation([NotNull] EPDDLParser.WorldValuationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateDesignDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateDesignDef([NotNull] EPDDLParser.StateDesignDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateDesignDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateDesignDef([NotNull] EPDDLParser.StateDesignDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.agentGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAgentGroup([NotNull] EPDDLParser.AgentGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.agentGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAgentGroup([NotNull] EPDDLParser.AgentGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] EPDDLParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] EPDDLParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.initialStateDescr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitialStateDescr([NotNull] EPDDLParser.InitialStateDescrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.initialStateDescr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitialStateDescr([NotNull] EPDDLParser.InitialStateDescrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.fTheoryFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFTheoryFormula([NotNull] EPDDLParser.FTheoryFormulaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.fTheoryFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFTheoryFormula([NotNull] EPDDLParser.FTheoryFormulaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.simpleFTheoryFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleFTheoryFormula([NotNull] EPDDLParser.SimpleFTheoryFormulaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.simpleFTheoryFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleFTheoryFormula([NotNull] EPDDLParser.SimpleFTheoryFormulaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionTypeName([NotNull] EPDDLParser.ActionTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionTypeName([NotNull] EPDDLParser.ActionTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] EPDDLParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] EPDDLParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] EPDDLParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] EPDDLParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.formulaOrEmpty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormulaOrEmpty([NotNull] EPDDLParser.FormulaOrEmptyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.formulaOrEmpty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormulaOrEmpty([NotNull] EPDDLParser.FormulaOrEmptyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.obsConditionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObsConditionDef([NotNull] EPDDLParser.ObsConditionDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.obsConditionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObsConditionDef([NotNull] EPDDLParser.ObsConditionDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.universalObsCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUniversalObsCond([NotNull] EPDDLParser.UniversalObsCondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.universalObsCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUniversalObsCond([NotNull] EPDDLParser.UniversalObsCondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.obsCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObsCondition([NotNull] EPDDLParser.ObsConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.obsCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObsCondition([NotNull] EPDDLParser.ObsConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.trivialObsCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrivialObsCond([NotNull] EPDDLParser.TrivialObsCondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.trivialObsCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrivialObsCond([NotNull] EPDDLParser.TrivialObsCondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.ifObsCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfObsCond([NotNull] EPDDLParser.IfObsCondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.ifObsCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfObsCond([NotNull] EPDDLParser.IfObsCondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.otherwiseObsCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOtherwiseObsCond([NotNull] EPDDLParser.OtherwiseObsCondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.otherwiseObsCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOtherwiseObsCond([NotNull] EPDDLParser.OtherwiseObsCondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.observingAgent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObservingAgent([NotNull] EPDDLParser.ObservingAgentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.observingAgent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObservingAgent([NotNull] EPDDLParser.ObservingAgentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.observingAgentGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObservingAgentGroup([NotNull] EPDDLParser.ObservingAgentGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.observingAgentGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObservingAgentGroup([NotNull] EPDDLParser.ObservingAgentGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.agentGroupName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAgentGroupName([NotNull] EPDDLParser.AgentGroupNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.agentGroupName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAgentGroupName([NotNull] EPDDLParser.AgentGroupNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicate([NotNull] EPDDLParser.PredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicate([NotNull] EPDDLParser.PredicateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeGroupsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionTypeGroupsDef([NotNull] EPDDLParser.ActionTypeGroupsDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeGroupsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionTypeGroupsDef([NotNull] EPDDLParser.ActionTypeGroupsDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeEventsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionTypeEventsDef([NotNull] EPDDLParser.ActionTypeEventsDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeEventsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionTypeEventsDef([NotNull] EPDDLParser.ActionTypeEventsDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventSignature([NotNull] EPDDLParser.EventSignatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventSignature([NotNull] EPDDLParser.EventSignatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeRelDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionTypeRelDef([NotNull] EPDDLParser.ActionTypeRelDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeRelDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionTypeRelDef([NotNull] EPDDLParser.ActionTypeRelDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionRelations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionRelations([NotNull] EPDDLParser.ActionRelationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionRelations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionRelations([NotNull] EPDDLParser.ActionRelationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventRelation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventRelation([NotNull] EPDDLParser.EventRelationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventRelation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventRelation([NotNull] EPDDLParser.EventRelationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventNamePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventNamePair([NotNull] EPDDLParser.EventNamePairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventNamePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventNamePair([NotNull] EPDDLParser.EventNamePairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeDesignDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionTypeDesignDef([NotNull] EPDDLParser.ActionTypeDesignDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeDesignDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionTypeDesignDef([NotNull] EPDDLParser.ActionTypeDesignDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.typedAgentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedAgentList([NotNull] EPDDLParser.TypedAgentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.typedAgentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedAgentList([NotNull] EPDDLParser.TypedAgentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.knowsWhether"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKnowsWhether([NotNull] EPDDLParser.KnowsWhetherContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.knowsWhether"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKnowsWhether([NotNull] EPDDLParser.KnowsWhetherContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.requirementKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRequirementKey([NotNull] EPDDLParser.RequirementKeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.requirementKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRequirementKey([NotNull] EPDDLParser.RequirementKeyContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
