//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Parser/EPDDLParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="EPDDLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IEPDDLParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.mainDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMainDef([NotNull] EPDDLParser.MainDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.domainDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDomainDef([NotNull] EPDDLParser.DomainDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.libraryDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibraryDef([NotNull] EPDDLParser.LibraryDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.problemDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProblemDef([NotNull] EPDDLParser.ProblemDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.domainItemDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDomainItemDef([NotNull] EPDDLParser.DomainItemDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.libraryItemDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibraryItemDef([NotNull] EPDDLParser.LibraryItemDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.problemItemDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProblemItemDef([NotNull] EPDDLParser.ProblemItemDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.domainLibrariesNameDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDomainLibrariesNameDef([NotNull] EPDDLParser.DomainLibrariesNameDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.problemDomainNameDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProblemDomainNameDef([NotNull] EPDDLParser.ProblemDomainNameDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.agentNamesDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgentNamesDef([NotNull] EPDDLParser.AgentNamesDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.agentGroupsListDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgentGroupsListDef([NotNull] EPDDLParser.AgentGroupsListDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.agentGroupDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgentGroupDef([NotNull] EPDDLParser.AgentGroupDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.objectNamesDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectNamesDef([NotNull] EPDDLParser.ObjectNamesDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.staticPredListDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStaticPredListDef([NotNull] EPDDLParser.StaticPredListDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.requireDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRequireDef([NotNull] EPDDLParser.RequireDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.typesDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypesDef([NotNull] EPDDLParser.TypesDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.predicateListDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicateListDef([NotNull] EPDDLParser.PredicateListDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.predicateDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicateDef([NotNull] EPDDLParser.PredicateDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.actionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionDef([NotNull] EPDDLParser.ActionDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.ownersDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOwnersDef([NotNull] EPDDLParser.OwnersDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.agentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgentList([NotNull] EPDDLParser.AgentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.eventsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventsDef([NotNull] EPDDLParser.EventsDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.eventDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventDef([NotNull] EPDDLParser.EventDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.effectDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEffectDef([NotNull] EPDDLParser.EffectDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] EPDDLParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.accessibilityDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessibilityDef([NotNull] EPDDLParser.AccessibilityDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.accessibilityRel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessibilityRel([NotNull] EPDDLParser.AccessibilityRelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.eventPreDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventPreDef([NotNull] EPDDLParser.EventPreDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.eventPostDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventPostDef([NotNull] EPDDLParser.EventPostDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.parametersDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParametersDef([NotNull] EPDDLParser.ParametersDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.modalityDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModalityDef([NotNull] EPDDLParser.ModalityDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.observabilityGroupsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObservabilityGroupsDef([NotNull] EPDDLParser.ObservabilityGroupsDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.postconditionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostconditionBlock([NotNull] EPDDLParser.PostconditionBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.postcondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostcondition([NotNull] EPDDLParser.PostconditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.simplePostcondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimplePostcondition([NotNull] EPDDLParser.SimplePostconditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.actionTypeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionTypeDef([NotNull] EPDDLParser.ActionTypeDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.stateDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateDef([NotNull] EPDDLParser.StateDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.initDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitDef([NotNull] EPDDLParser.InitDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.worldsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWorldsDef([NotNull] EPDDLParser.WorldsDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.worldDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWorldDef([NotNull] EPDDLParser.WorldDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.goalDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoalDef([NotNull] EPDDLParser.GoalDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.actionConditionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionConditionDef([NotNull] EPDDLParser.ActionConditionDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.actionTypeSignatureDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionTypeSignatureDef([NotNull] EPDDLParser.ActionTypeSignatureDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.actionPreDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionPreDef([NotNull] EPDDLParser.ActionPreDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.actionObsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionObsDef([NotNull] EPDDLParser.ActionObsDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.typedIdentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedIdentList([NotNull] EPDDLParser.TypedIdentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.typedVariableList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedVariableList([NotNull] EPDDLParser.TypedVariableListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.typedAgentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedAgentList([NotNull] EPDDLParser.TypedAgentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] EPDDLParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.reservedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReservedType([NotNull] EPDDLParser.ReservedTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormula([NotNull] EPDDLParser.FormulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.conditionFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionFormula([NotNull] EPDDLParser.ConditionFormulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] EPDDLParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.atomicCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomicCondition([NotNull] EPDDLParser.AtomicConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.predicateFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicateFormula([NotNull] EPDDLParser.PredicateFormulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.atomicEqFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomicEqFormula([NotNull] EPDDLParser.AtomicEqFormulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] EPDDLParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.groundTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroundTerm([NotNull] EPDDLParser.GroundTermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.modality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModality([NotNull] EPDDLParser.ModalityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.singleModality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleModality([NotNull] EPDDLParser.SingleModalityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.groupModality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupModality([NotNull] EPDDLParser.GroupModalityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.modalityLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModalityLabel([NotNull] EPDDLParser.ModalityLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.modalityAgent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModalityAgent([NotNull] EPDDLParser.ModalityAgentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.modalityAgentGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModalityAgentGroup([NotNull] EPDDLParser.ModalityAgentGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.allAgents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAllAgents([NotNull] EPDDLParser.AllAgentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.predicateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicateName([NotNull] EPDDLParser.PredicateNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.domainName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDomainName([NotNull] EPDDLParser.DomainNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.problemName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProblemName([NotNull] EPDDLParser.ProblemNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.libraryName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibraryName([NotNull] EPDDLParser.LibraryNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.stateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateName([NotNull] EPDDLParser.StateNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.worldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWorldName([NotNull] EPDDLParser.WorldNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.actionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionName([NotNull] EPDDLParser.ActionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.eventName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventName([NotNull] EPDDLParser.EventNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.agentName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgentName([NotNull] EPDDLParser.AgentNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.modalityName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModalityName([NotNull] EPDDLParser.ModalityNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.staticPredDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStaticPredDef([NotNull] EPDDLParser.StaticPredDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.genericName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericName([NotNull] EPDDLParser.GenericNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.stateWorldsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateWorldsDef([NotNull] EPDDLParser.StateWorldsDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.stateRelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateRelDef([NotNull] EPDDLParser.StateRelDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.stateRelations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateRelations([NotNull] EPDDLParser.StateRelationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.worldRelation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWorldRelation([NotNull] EPDDLParser.WorldRelationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.worldNamePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWorldNamePair([NotNull] EPDDLParser.WorldNamePairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.stateValDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateValDef([NotNull] EPDDLParser.StateValDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.stateValuation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateValuation([NotNull] EPDDLParser.StateValuationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.worldValuation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWorldValuation([NotNull] EPDDLParser.WorldValuationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.stateDesignDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateDesignDef([NotNull] EPDDLParser.StateDesignDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.agentGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgentGroup([NotNull] EPDDLParser.AgentGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.initialStateDescr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitialStateDescr([NotNull] EPDDLParser.InitialStateDescrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.fTheoryFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFTheoryFormula([NotNull] EPDDLParser.FTheoryFormulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.simpleFTheoryFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleFTheoryFormula([NotNull] EPDDLParser.SimpleFTheoryFormulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.actionTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionTypeName([NotNull] EPDDLParser.ActionTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] EPDDLParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] EPDDLParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.formulaOrEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormulaOrEmpty([NotNull] EPDDLParser.FormulaOrEmptyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.obsConditionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObsConditionDef([NotNull] EPDDLParser.ObsConditionDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.universalObsCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUniversalObsCond([NotNull] EPDDLParser.UniversalObsCondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.obsCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObsCondition([NotNull] EPDDLParser.ObsConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.trivialObsCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrivialObsCond([NotNull] EPDDLParser.TrivialObsCondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.ifObsCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfObsCond([NotNull] EPDDLParser.IfObsCondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.otherwiseObsCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherwiseObsCond([NotNull] EPDDLParser.OtherwiseObsCondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.observingAgent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObservingAgent([NotNull] EPDDLParser.ObservingAgentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.observingAgentGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObservingAgentGroup([NotNull] EPDDLParser.ObservingAgentGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.agentGroupName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgentGroupName([NotNull] EPDDLParser.AgentGroupNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicate([NotNull] EPDDLParser.PredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.actionTypeGroupsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionTypeGroupsDef([NotNull] EPDDLParser.ActionTypeGroupsDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.actionTypeEventsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionTypeEventsDef([NotNull] EPDDLParser.ActionTypeEventsDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.eventSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventSignature([NotNull] EPDDLParser.EventSignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.actionTypeRelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionTypeRelDef([NotNull] EPDDLParser.ActionTypeRelDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.actionRelations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionRelations([NotNull] EPDDLParser.ActionRelationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.eventRelation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventRelation([NotNull] EPDDLParser.EventRelationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.eventNamePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventNamePair([NotNull] EPDDLParser.EventNamePairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.actionTypeDesignDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionTypeDesignDef([NotNull] EPDDLParser.ActionTypeDesignDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.knowsWhether"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKnowsWhether([NotNull] EPDDLParser.KnowsWhetherContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EPDDLParser.requirementKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRequirementKey([NotNull] EPDDLParser.RequirementKeyContext context);
}
