//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EPDDLParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="EPDDLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IEPDDLParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.mainDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainDef([NotNull] EPDDLParser.MainDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.mainDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainDef([NotNull] EPDDLParser.MainDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.domainDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomainDef([NotNull] EPDDLParser.DomainDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.domainDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomainDef([NotNull] EPDDLParser.DomainDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.libraryDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLibraryDef([NotNull] EPDDLParser.LibraryDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.libraryDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLibraryDef([NotNull] EPDDLParser.LibraryDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.problemDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProblemDef([NotNull] EPDDLParser.ProblemDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.problemDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProblemDef([NotNull] EPDDLParser.ProblemDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.domainItemDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomainItemDef([NotNull] EPDDLParser.DomainItemDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.domainItemDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomainItemDef([NotNull] EPDDLParser.DomainItemDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.libraryItemDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLibraryItemDef([NotNull] EPDDLParser.LibraryItemDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.libraryItemDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLibraryItemDef([NotNull] EPDDLParser.LibraryItemDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.problemItemDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProblemItemDef([NotNull] EPDDLParser.ProblemItemDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.problemItemDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProblemItemDef([NotNull] EPDDLParser.ProblemItemDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.domainLibrariesNameDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomainLibrariesNameDef([NotNull] EPDDLParser.DomainLibrariesNameDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.domainLibrariesNameDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomainLibrariesNameDef([NotNull] EPDDLParser.DomainLibrariesNameDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.problemDomainNameDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProblemDomainNameDef([NotNull] EPDDLParser.ProblemDomainNameDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.problemDomainNameDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProblemDomainNameDef([NotNull] EPDDLParser.ProblemDomainNameDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.agentNamesDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAgentNamesDef([NotNull] EPDDLParser.AgentNamesDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.agentNamesDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAgentNamesDef([NotNull] EPDDLParser.AgentNamesDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.agentGroupsListDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAgentGroupsListDef([NotNull] EPDDLParser.AgentGroupsListDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.agentGroupsListDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAgentGroupsListDef([NotNull] EPDDLParser.AgentGroupsListDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.agentGroupDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAgentGroupDef([NotNull] EPDDLParser.AgentGroupDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.agentGroupDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAgentGroupDef([NotNull] EPDDLParser.AgentGroupDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.objectNamesDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectNamesDef([NotNull] EPDDLParser.ObjectNamesDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.objectNamesDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectNamesDef([NotNull] EPDDLParser.ObjectNamesDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.staticPredListDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStaticPredListDef([NotNull] EPDDLParser.StaticPredListDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.staticPredListDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStaticPredListDef([NotNull] EPDDLParser.StaticPredListDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.requireDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequireDef([NotNull] EPDDLParser.RequireDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.requireDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequireDef([NotNull] EPDDLParser.RequireDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.typesDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypesDef([NotNull] EPDDLParser.TypesDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.typesDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypesDef([NotNull] EPDDLParser.TypesDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.predicateListDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicateListDef([NotNull] EPDDLParser.PredicateListDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.predicateListDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicateListDef([NotNull] EPDDLParser.PredicateListDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.predicateDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicateDef([NotNull] EPDDLParser.PredicateDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.predicateDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicateDef([NotNull] EPDDLParser.PredicateDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionDef([NotNull] EPDDLParser.ActionDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionDef([NotNull] EPDDLParser.ActionDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.parametersDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParametersDef([NotNull] EPDDLParser.ParametersDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.parametersDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParametersDef([NotNull] EPDDLParser.ParametersDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.modalityDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModalityDef([NotNull] EPDDLParser.ModalityDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.modalityDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModalityDef([NotNull] EPDDLParser.ModalityDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.observabilityGroupsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObservabilityGroupsDef([NotNull] EPDDLParser.ObservabilityGroupsDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.observabilityGroupsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObservabilityGroupsDef([NotNull] EPDDLParser.ObservabilityGroupsDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventDef([NotNull] EPDDLParser.EventDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventDef([NotNull] EPDDLParser.EventDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventPreDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventPreDef([NotNull] EPDDLParser.EventPreDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventPreDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventPreDef([NotNull] EPDDLParser.EventPreDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventPostDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventPostDef([NotNull] EPDDLParser.EventPostDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventPostDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventPostDef([NotNull] EPDDLParser.EventPostDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.postconditionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostconditionBlock([NotNull] EPDDLParser.PostconditionBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.postconditionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostconditionBlock([NotNull] EPDDLParser.PostconditionBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.postcondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostcondition([NotNull] EPDDLParser.PostconditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.postcondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostcondition([NotNull] EPDDLParser.PostconditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.simplePostcondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimplePostcondition([NotNull] EPDDLParser.SimplePostconditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.simplePostcondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimplePostcondition([NotNull] EPDDLParser.SimplePostconditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionTypeDef([NotNull] EPDDLParser.ActionTypeDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionTypeDef([NotNull] EPDDLParser.ActionTypeDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateDef([NotNull] EPDDLParser.StateDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateDef([NotNull] EPDDLParser.StateDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.initDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitDef([NotNull] EPDDLParser.InitDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.initDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitDef([NotNull] EPDDLParser.InitDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.goalDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoalDef([NotNull] EPDDLParser.GoalDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.goalDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoalDef([NotNull] EPDDLParser.GoalDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionConditionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionConditionDef([NotNull] EPDDLParser.ActionConditionDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionConditionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionConditionDef([NotNull] EPDDLParser.ActionConditionDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeSignatureDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionTypeSignatureDef([NotNull] EPDDLParser.ActionTypeSignatureDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeSignatureDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionTypeSignatureDef([NotNull] EPDDLParser.ActionTypeSignatureDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionPreDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionPreDef([NotNull] EPDDLParser.ActionPreDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionPreDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionPreDef([NotNull] EPDDLParser.ActionPreDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionObsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionObsDef([NotNull] EPDDLParser.ActionObsDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionObsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionObsDef([NotNull] EPDDLParser.ActionObsDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.typedIdentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedIdentList([NotNull] EPDDLParser.TypedIdentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.typedIdentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedIdentList([NotNull] EPDDLParser.TypedIdentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.typedVariableList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedVariableList([NotNull] EPDDLParser.TypedVariableListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.typedVariableList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedVariableList([NotNull] EPDDLParser.TypedVariableListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] EPDDLParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] EPDDLParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.reservedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReservedType([NotNull] EPDDLParser.ReservedTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.reservedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReservedType([NotNull] EPDDLParser.ReservedTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormula([NotNull] EPDDLParser.FormulaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormula([NotNull] EPDDLParser.FormulaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.conditionFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionFormula([NotNull] EPDDLParser.ConditionFormulaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.conditionFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionFormula([NotNull] EPDDLParser.ConditionFormulaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] EPDDLParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] EPDDLParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.atomicCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomicCondition([NotNull] EPDDLParser.AtomicConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.atomicCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomicCondition([NotNull] EPDDLParser.AtomicConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.predicateFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicateFormula([NotNull] EPDDLParser.PredicateFormulaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.predicateFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicateFormula([NotNull] EPDDLParser.PredicateFormulaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.atomicEqFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomicEqFormula([NotNull] EPDDLParser.AtomicEqFormulaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.atomicEqFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomicEqFormula([NotNull] EPDDLParser.AtomicEqFormulaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] EPDDLParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] EPDDLParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.groundTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroundTerm([NotNull] EPDDLParser.GroundTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.groundTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroundTerm([NotNull] EPDDLParser.GroundTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.modality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModality([NotNull] EPDDLParser.ModalityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.modality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModality([NotNull] EPDDLParser.ModalityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.singleModality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleModality([NotNull] EPDDLParser.SingleModalityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.singleModality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleModality([NotNull] EPDDLParser.SingleModalityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.groupModality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupModality([NotNull] EPDDLParser.GroupModalityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.groupModality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupModality([NotNull] EPDDLParser.GroupModalityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.modalityLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModalityLabel([NotNull] EPDDLParser.ModalityLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.modalityLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModalityLabel([NotNull] EPDDLParser.ModalityLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.modalityAgent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModalityAgent([NotNull] EPDDLParser.ModalityAgentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.modalityAgent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModalityAgent([NotNull] EPDDLParser.ModalityAgentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.modalityAgentGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModalityAgentGroup([NotNull] EPDDLParser.ModalityAgentGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.modalityAgentGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModalityAgentGroup([NotNull] EPDDLParser.ModalityAgentGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.allAgents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAllAgents([NotNull] EPDDLParser.AllAgentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.allAgents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAllAgents([NotNull] EPDDLParser.AllAgentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.predicateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicateName([NotNull] EPDDLParser.PredicateNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.predicateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicateName([NotNull] EPDDLParser.PredicateNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.domainName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomainName([NotNull] EPDDLParser.DomainNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.domainName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomainName([NotNull] EPDDLParser.DomainNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.problemName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProblemName([NotNull] EPDDLParser.ProblemNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.problemName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProblemName([NotNull] EPDDLParser.ProblemNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.libraryName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLibraryName([NotNull] EPDDLParser.LibraryNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.libraryName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLibraryName([NotNull] EPDDLParser.LibraryNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateName([NotNull] EPDDLParser.StateNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateName([NotNull] EPDDLParser.StateNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.worldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWorldName([NotNull] EPDDLParser.WorldNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.worldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWorldName([NotNull] EPDDLParser.WorldNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionName([NotNull] EPDDLParser.ActionNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionName([NotNull] EPDDLParser.ActionNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventName([NotNull] EPDDLParser.EventNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventName([NotNull] EPDDLParser.EventNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.agentName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAgentName([NotNull] EPDDLParser.AgentNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.agentName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAgentName([NotNull] EPDDLParser.AgentNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.modalityName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModalityName([NotNull] EPDDLParser.ModalityNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.modalityName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModalityName([NotNull] EPDDLParser.ModalityNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.staticPredDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStaticPredDef([NotNull] EPDDLParser.StaticPredDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.staticPredDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStaticPredDef([NotNull] EPDDLParser.StaticPredDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.genericName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericName([NotNull] EPDDLParser.GenericNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.genericName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericName([NotNull] EPDDLParser.GenericNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateWorldsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateWorldsDef([NotNull] EPDDLParser.StateWorldsDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateWorldsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateWorldsDef([NotNull] EPDDLParser.StateWorldsDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateRelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateRelDef([NotNull] EPDDLParser.StateRelDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateRelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateRelDef([NotNull] EPDDLParser.StateRelDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateRelations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateRelations([NotNull] EPDDLParser.StateRelationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateRelations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateRelations([NotNull] EPDDLParser.StateRelationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.worldRelation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWorldRelation([NotNull] EPDDLParser.WorldRelationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.worldRelation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWorldRelation([NotNull] EPDDLParser.WorldRelationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.worldNamePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWorldNamePair([NotNull] EPDDLParser.WorldNamePairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.worldNamePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWorldNamePair([NotNull] EPDDLParser.WorldNamePairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateValDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateValDef([NotNull] EPDDLParser.StateValDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateValDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateValDef([NotNull] EPDDLParser.StateValDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateValuation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateValuation([NotNull] EPDDLParser.StateValuationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateValuation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateValuation([NotNull] EPDDLParser.StateValuationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.worldValuation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWorldValuation([NotNull] EPDDLParser.WorldValuationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.worldValuation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWorldValuation([NotNull] EPDDLParser.WorldValuationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.stateDesignDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateDesignDef([NotNull] EPDDLParser.StateDesignDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.stateDesignDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateDesignDef([NotNull] EPDDLParser.StateDesignDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.agentGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAgentGroup([NotNull] EPDDLParser.AgentGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.agentGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAgentGroup([NotNull] EPDDLParser.AgentGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] EPDDLParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] EPDDLParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.initialStateDescr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitialStateDescr([NotNull] EPDDLParser.InitialStateDescrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.initialStateDescr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitialStateDescr([NotNull] EPDDLParser.InitialStateDescrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.fTheoryFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFTheoryFormula([NotNull] EPDDLParser.FTheoryFormulaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.fTheoryFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFTheoryFormula([NotNull] EPDDLParser.FTheoryFormulaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.simpleFTheoryFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleFTheoryFormula([NotNull] EPDDLParser.SimpleFTheoryFormulaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.simpleFTheoryFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleFTheoryFormula([NotNull] EPDDLParser.SimpleFTheoryFormulaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionTypeName([NotNull] EPDDLParser.ActionTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionTypeName([NotNull] EPDDLParser.ActionTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] EPDDLParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] EPDDLParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] EPDDLParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] EPDDLParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.formulaOrEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormulaOrEmpty([NotNull] EPDDLParser.FormulaOrEmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.formulaOrEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormulaOrEmpty([NotNull] EPDDLParser.FormulaOrEmptyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.obsConditionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObsConditionDef([NotNull] EPDDLParser.ObsConditionDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.obsConditionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObsConditionDef([NotNull] EPDDLParser.ObsConditionDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.universalObsCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUniversalObsCond([NotNull] EPDDLParser.UniversalObsCondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.universalObsCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUniversalObsCond([NotNull] EPDDLParser.UniversalObsCondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.obsCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObsCondition([NotNull] EPDDLParser.ObsConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.obsCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObsCondition([NotNull] EPDDLParser.ObsConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.trivialObsCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrivialObsCond([NotNull] EPDDLParser.TrivialObsCondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.trivialObsCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrivialObsCond([NotNull] EPDDLParser.TrivialObsCondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.ifObsCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfObsCond([NotNull] EPDDLParser.IfObsCondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.ifObsCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfObsCond([NotNull] EPDDLParser.IfObsCondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.otherwiseObsCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOtherwiseObsCond([NotNull] EPDDLParser.OtherwiseObsCondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.otherwiseObsCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOtherwiseObsCond([NotNull] EPDDLParser.OtherwiseObsCondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.observingAgent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObservingAgent([NotNull] EPDDLParser.ObservingAgentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.observingAgent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObservingAgent([NotNull] EPDDLParser.ObservingAgentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.observingAgentGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObservingAgentGroup([NotNull] EPDDLParser.ObservingAgentGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.observingAgentGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObservingAgentGroup([NotNull] EPDDLParser.ObservingAgentGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.agentGroupName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAgentGroupName([NotNull] EPDDLParser.AgentGroupNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.agentGroupName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAgentGroupName([NotNull] EPDDLParser.AgentGroupNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicate([NotNull] EPDDLParser.PredicateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicate([NotNull] EPDDLParser.PredicateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeGroupsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionTypeGroupsDef([NotNull] EPDDLParser.ActionTypeGroupsDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeGroupsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionTypeGroupsDef([NotNull] EPDDLParser.ActionTypeGroupsDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeEventsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionTypeEventsDef([NotNull] EPDDLParser.ActionTypeEventsDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeEventsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionTypeEventsDef([NotNull] EPDDLParser.ActionTypeEventsDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventSignature([NotNull] EPDDLParser.EventSignatureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventSignature([NotNull] EPDDLParser.EventSignatureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeRelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionTypeRelDef([NotNull] EPDDLParser.ActionTypeRelDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeRelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionTypeRelDef([NotNull] EPDDLParser.ActionTypeRelDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionRelations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionRelations([NotNull] EPDDLParser.ActionRelationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionRelations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionRelations([NotNull] EPDDLParser.ActionRelationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventRelation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventRelation([NotNull] EPDDLParser.EventRelationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventRelation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventRelation([NotNull] EPDDLParser.EventRelationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.eventNamePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventNamePair([NotNull] EPDDLParser.EventNamePairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.eventNamePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventNamePair([NotNull] EPDDLParser.EventNamePairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.actionTypeDesignDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionTypeDesignDef([NotNull] EPDDLParser.ActionTypeDesignDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.actionTypeDesignDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionTypeDesignDef([NotNull] EPDDLParser.ActionTypeDesignDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.typedAgentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedAgentList([NotNull] EPDDLParser.TypedAgentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.typedAgentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedAgentList([NotNull] EPDDLParser.TypedAgentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.knowsWhether"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKnowsWhether([NotNull] EPDDLParser.KnowsWhetherContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.knowsWhether"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKnowsWhether([NotNull] EPDDLParser.KnowsWhetherContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EPDDLParser.requirementKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequirementKey([NotNull] EPDDLParser.RequirementKeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EPDDLParser.requirementKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequirementKey([NotNull] EPDDLParser.RequirementKeyContext context);
}
